projects:
  fictionfriendzyapi:
    schemaPath: amplify/backend/api/fictionfriendzyapi/build/schema.graphql
    includes:
      - src/graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/graphql.ts
        docsFilePath: src
        region: us-west-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
